In [ ]:
import pandas as pd
#Pandas is built on top of NumPy and provides high-level data structures like Series and DataFrame for fast and efficient data manipulation.

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0
1    -118.30     34.26                43.0       1510.0           310.0
2    -117.81     33.78                27.0       3589.0           507.0
3    -118.36     33.82                28.0         67.0            15.0
4    -119.67     36.33                19.0       1241.0           244.0

   population  households  median_income  median_house_value
0      1537.0       606.0         6.6085            344700.0
1       809.0       277.0         3.5990            176500.0
2      1484.0       495.0         5.7934            270500.0
3        49.0        11.0         6.1359            330000.0
4       850.0       237.0         2.9375             81700.0

In [ ]:
# Check for missing values
print(df.isnull().sum())
print(df.columns)

df.dropna(inplace=True)

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64
Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
# Check for duplicate rows
print(df.duplicated().sum())

0

In [ ]:
# Drop duplicate rows
df.drop_duplicates(inplace=True)

In [ ]:
#Checking Data Types: Use dtypes to see the data type of each column.
#Converting Data Types: Use astype() to convert data types.
print(df.dtypes)

# Convert a column to numeric
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce') # Placeholder - causes KeyError

# Convert a column to datetime
df['date_column'] = pd.to_datetime(df['date_column']) # Placeholder - causes KeyError

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

KeyError: 'date_column'

In [ ]:
 #Filter rows where 'age' is greater than 30
filtered_df = df[df['latitude'] < 30]

# Sort the DataFrame by 'age' in descending order
sorted_df = df.sort_values('housing_median_age', ascending=False)
print(filtered_df)
print(sorted_df)

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value]
Index: []
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2972    -118.14     34.17                52.0       2667.0           486.0
2544    -118.28     34.09                52.0       1739.0           464.0
2507    -118.15     33.77                52.0       2204.0           498.0
2604    -118.13     34.16                52.0       1872.0           357.0
384     -122.42     37.76                52.0       2038.0           629.0
...         ...       ...                 ...          ...             ...
2452    -117.64     33.87                 2.0      17470.0          2727.0
1271    -120.98     37.59                 2.0       5042.0           834.0
2429    -117.20     33.58                 2.0      30450.0          5033.0
842     -117.95     35.08                 1.0         83.0            15.0
1115    -116.95     33.86                 1.0          6.0             2.0

      population  households  median_income  median_house_value
2972      1681.0       504.0         4.0524            173100.0
2544       938.0       482.0         2.4429            228800.0
2507       899.0       445.0         4.1765            393900.0
2604       984.0       364.0         4.0000            250400.0
384       2007.0       596.0         2.5701            266700.0
...          ...         ...            ...                 ...
2452      5964.0      1985.0         6.2308            257900.0
1271      2784.0       787.0         4.6484            145900.0
2429      9419.0      3197.0         4.5936            174300.0
842         32.0        15.0         4.8750            141700.0
1115         8.0         2.0         1.6250             55000.0

[3000 rows x 9 columns]

In [ ]:
#Pandas makes it easy to identify and remove outliers based on statistical methods like the interquartile range (IQR).
Q1 = df['median_house_value'].quantile(0.25)
Q3 = df['median_house_value'].quantile(0.75)
IQR = Q3 - Q1

df = df[~(
    (df['median_house_value'] < (Q1 - 1.5 * IQR)) |
    (df['median_house_value'] > (Q3 + 1.5 * IQR))
)]

print(df)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2994    -117.93     33.86                35.0        931.0           181.0
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2994       516.0       174.0         5.5867            182500.0
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0

[2822 rows x 9 columns]

In [ ]:
import pandas as pd

# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'Chicago', 'New York', 'San Francisco']}

df = pd.DataFrame(data)

# Filtering rows where Age is greater than 30
filtered_df = df[df['Age'] > 30]
print(filtered_df)

      Name  Age           City
2  Charlie   35       New York
3    David   40  San Francisco

In [ ]:
# Filtering with multiple conditions (AND condition)
filtered_df = df[(df['Age'] > 30) & (df['City'] == 'New York')]
print(filtered_df)

      Name  Age      City
2  Charlie   35  New York

In [ ]:
# Filtering rows where Age > 30 OR City is New York
filtered_df = df[(df['Age'] > 30) | (df['City'] == 'New York')]
print(filtered_df)

      Name  Age           City
0    Alice   25       New York
2  Charlie   35       New York
3    David   40  San Francisco

In [ ]:
# Exclude rows where City is 'Chicago'
filtered_df = df[~(df['City'] == 'Chicago')]
print(filtered_df)

      Name  Age           City
0    Alice   25       New York
2  Charlie   35       New York
3    David   40  San Francisco

In [ ]:
# Using .query() method
filtered_df = df.query("Age > 30 and City == 'New York'")
print(filtered_df)

      Name  Age      City
2  Charlie   35  New York

In [ ]:
import pandas as pd

# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 35, 40, 29],
        'City': ['New York', 'Chicago', 'New York', 'San Francisco', 'Los Angeles']}

df = pd.DataFrame(data)

# Filtering rows where City is either 'New York' or 'San Francisco'
filtered_df = df[df['City'].isin(['New York', 'San Francisco'])]
print(filtered_df)

      Name  Age           City
0    Alice   25       New York
2  Charlie   35       New York
3    David   40  San Francisco

In [ ]:
# Excluding rows where City is 'New York' or 'San Francisco'
filtered_df = df[~df['City'].isin(['New York', 'San Francisco'])]
print(filtered_df)

  Name  Age         City
1  Bob   30      Chicago
4  Eve   29  Los Angeles

In [ ]:
# Filtering rows where Name starts with 'A'
filtered_df = df[df['Name'].str.contains('A', case=False)]  # case=False makes it case-insensitive
print(filtered_df)

      Name  Age           City
0    Alice   25       New York
2  Charlie   35       New York
3    David   40  San Francisco

In [ ]:
# Filtering rows where City contains 'York'
filtered_df = df[df['City'].str.contains('York', case=False)]
print(filtered_df)

      Name  Age      City
0    Alice   25  New York
2  Charlie   35  New York

In [ ]:
# Using .loc for filtering and selecting specific columns
#More readable than df[...] for selecting columns.
#Faster execution when working with large datasets.
#Great for clean, structured data extraction.
filtered_df = df.loc[df['Age'] > 30, ['Name', 'City']]
print(filtered_df)

      Name           City
2  Charlie       New York
3    David  San Francisco

In [ ]:
# Selecting only columns with 'Name' or 'Age'
filtered_df = df.filter(items=['Name', 'Age'])
print(filtered_df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4      Eve   29

In [ ]:
dictionary = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

# Creating series of Dictionary type
sd = pd.Series(dictionary)

In [ ]:
# Defining 2darray
Data = [[2, 3, 4], [5, 6, 7]]

# Creating series of 2darray
snd = pd.Series(Data)

In [ ]:
# Define Dictionary 1
dict1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4}

# Define Dictionary 2
dict2 = {'a': 5, 'b': 6, 'c': 7, 'd': 8, 'e': 9}

# Define Data with dict1 and dict2
Data = {'first': dict1, 'second': dict2}

# Create DataFrame
df = pd.DataFrame(Data)

df

   first  second
a    1.0       5
b    2.0       6
c    3.0       7
d    4.0       8
e    NaN       9

In [ ]:
import pandas as pd
data_c = [
 {'A': 5, 'B': 0, 'C': 3, 'D': 3},
 {'A': 7, 'B': 9, 'C': 3, 'D': 5},
 {'A': 2, 'B': 4, 'C': 7, 'D': 6}]

pd.DataFrame.from_dict(data_c, orient='columns')

   A  B  C  D
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6